name: Export Secrets to Artifact

on:
  workflow_dispatch:  # Trigger manually

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Export JSON secret to a file
        run: echo '${{ secrets.GROQ_API_KEYS }}' > api_keys.json

      - name: Upload JSON secret as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-keys
          path: api_keys.json
